apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-python-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cicd-python-app

  template:
    metadata:
      labels:
        app: cicd-python-app

    spec:
      containers:
        - name: cicd-python-app
          image: IMAGE_URI
          ports:
            - containerPort: 5000