apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-python-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cicd-python-app

  template:
    metadata:
      labels:
        app: cicd-python-app

    spec:
      containers:
        - name: cicd-python-app
          image: 691914216603.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app:d7f4c40f960bf384b1fc008d05bf3059f33054cb
          ports:
            - containerPort: 5000