apiVersion: v1
kind: Service
metadata:
  name: cicd-python-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: cicd-python-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
