name: Python CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run automated tests
        run: pytest

      - name: Inspect GitHub OIDC claims
        shell: bash
        run: |
          echo "Requesting GitHub OIDC token..."

          RESPONSE=$(curl -sS \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          TOKEN=$(echo "$RESPONSE" | jq -r '.value')

          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
            echo "Failed to obtain GitHub OIDC token"
            echo "$RESPONSE"
            exit 1
          fi

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          PAYLOAD=$(echo "$PAYLOAD" | tr '_-' '/+')

          case $((${#PAYLOAD} % 4)) in
            2)
              PAYLOAD="${PAYLOAD}=="
              ;;
            3)
              PAYLOAD="${PAYLOAD}="
              ;;
          esac

          echo "GitHub OIDC claims:"
          echo "$PAYLOAD" | base64 -d | jq '{
            iss,
            aud,
            sub,
            repository,
            repository_id,
            repository_owner,
            repository_owner_id,
            ref,
            sha,
            workflow,
            actor
          }'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHubActions

      - name: Verify AWS identity
        run: |
          echo "AWS identity:"
          aws sts get-caller-identity

          echo "AWS region:"
          echo "$AWS_REGION"

          echo "Credential expiration:"
          echo "$AWS_CREDENTIAL_EXPIRATION"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building image..."
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          docker build \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
            .

      - name: Show Docker images
        run: docker images

      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Pushing Docker image to Amazon ECR..."

          docker push \
            "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Show pushed image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Successfully pushed:"
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Update kubeconfig for EKS
        run: |
        aws eks update-kubeconfig \
        --name cicd-eks-cluster \
        --region ap-southeast-1

      - name: Deploy new image to EKS
        run: |
          kubectl set image deployment/cicd-python-app \
            cicd-python-app=691914216603.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app:${{ github.sha }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/cicd-python-app \
            --timeout=180s

      - name: Verify deployed image
          run: |
            kubectl get deployment cicd-python-app \
              -o jsonpath='{.spec.template.spec.containers[0].image}{"\n"}'

      - name: Show running pods
          run: |
            kubectl get pods -l app=cicd-python-app -o wide