name: My First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: Show repository files
        run: ls -la

      - name: Show operating system
        run: uname -a

      - name: Run first CI command
        run: echo "CI pipeline is working"